export const CLIENT_INFO_OBTAINED = 'CLIENT_INFO_OBTAINED';
export const LOGOUT = 'LOGOUT';
export const POLL_LOADED = 'POLL_LOADED';
export const POLLS_LOADED = 'POLLS_LOADED';
export const NOTIFICATION_DISMISSED = 'NOTIFICATION_DISMISSED';
export const PRESS_LOGIN_BUTTON = 'PRESS_LOGIN_BUTTON';
export const PRESS_CLOSE_BUTTON = 'PRESS_CLOSE_BUTTON';
